In [58]:
import pandas as pd
import numpy as np
import scipy.stats
import matplotlib.pyplot as plt
import seaborn as sns
import requests
from matplotlib.ticker import FuncFormatter
from matplotlib.dates import *

In [59]:
from config import DRIVER as driver

In [60]:
def to_list(cursor):
    return list(map(dict, cursor))

def to_data_frame(cursor):
    return pd.DataFrame(to_list(cursor))

def get_transactions(ind, am):
    url = "http://127.0.0.1:28081/get_outs"
    # Define the JSON payload
    payload = {"outputs":[{"amount": am, "index":ind}], "get_txid": True}
    # Define the headers
    headers = {
        "Content-Type": "application/json"
    }

    # Make the POST request
    response = requests.post(url, json=payload, headers=headers)
    return response.json()

First we will get the number of inputs with a mix in equal to 0. Remember this data has been creaed in a local tesnet, so the number with mixin equal to 0 may be elevated to show the privicy risk of using mixin 0. Rememebre that mixin 0 is not recommended for privacy reasons and you can no longer use it in the Monero main network.

In [61]:
with driver.session() as session:
    num_inputs = to_list(session.run(query=  """MATCH (i:Input) RETURN count(i)"""))[0]['count(i)']
    num_inputs_mix_0 = to_list(session.run(query=  """MATCH (i:Input) WHERE i.mixin = '0' RETURN count(i)"""))[0]['count(i)']

print(f"Number of inputs: {num_inputs}")
print(f"\nNumber of inputs with mixin equal to 0: {num_inputs_mix_0}. This inputs do not have the benefits of ring signatures")

Number of inputs: 4641

Number of inputs with mixin equal to 0: 766. This inputs do not have the benefits of ring signatures

Our next step is to get all the information of those inputs with mixins equal to 0 to see what information we can get from them.

In [62]:
query = """MATCH (i:Input)-[:TX_INPUT]->(t:Transactions)
            WHERE i.mixin = '0'
            RETURN i, t"""

with driver.session() as session:
    data = to_list(session.run(query=query))
    
    rows = []
    for record in data:
        input_node = record['i']
        transaction_node = record['t']
        row = {
                    'input_mixin': input_node.get('mixin'),
                    'input_anonset': input_node.get('anonset'),
                    'input_id': input_node.get('id'),
                    'input_value': input_node.get('value'),
                    'key_offset': input_node.get('key_offset'),
                    'transaction_fee': transaction_node.get('fee'),
                    'transaction_id': transaction_node.get('id'),
                    'transaction_hash': transaction_node.get('hash')
                }
        rows.append(row)
inputs = pd.DataFrame(rows)
inputs

,input_mixin,input_anonset,input_id,input_value,key_offset,transaction_fee,transaction_id,transaction_hash
0,0,63,i0,90000000000,[3],4268127321,t65,fbc9c915ebe08091e4bd58d039289c169dd1852a481715...
1,0,64,i1,10000000000000,[2],4268127321,t65,fbc9c915ebe08091e4bd58d039289c169dd1852a481715...
2,0,64,i2,10000000000000,[1],4268127321,t65,fbc9c915ebe08091e4bd58d039289c169dd1852a481715...
3,0,65,i3,7000000000000,[0],2458473645,t66,059b07e3ab70b55b93339026dd021e3bc5f1c65d70b11b...
4,0,65,i4,10000000000000,[3],3212403907,t67,6d6377e0fa4143181e7ac1b36216ad7e3d50a4309a7c43...
...,...,...,...,...,...,...,...,...
761,0,26,i761,9000000000000,[19],4946746849,t390,3115a8abbc0fe5b14b7ba1c996957df72c8703809337ef...
762,0,334,i762,10000000000000,[63],4946746849,t390,3115a8abbc0fe5b14b7ba1c996957df72c8703809337ef...
763,0,216,i763,90000000000,[144],4946746849,t390,3115a8abbc0fe5b14b7ba1c996957df72c8703809337ef...
764,0,59,i764,600000000000,[36],4946746849,t390,3115a8abbc0fe5b14b7ba1c996957df72c8703809337ef...
765,0,244,i765,500000000000,[140],4946746849,t390,3115a8abbc0fe5b14b7ba1c996957df72c8703809337ef...

Notice that there are key_offset that repeat. This is because the key_offset it point us at the output of some previous block, and that block can have multiple output. Is the key (which is an information will get on the next steps) along with the key_offset that will help us to identify the output that is being spent.

In [72]:
k_offsets_mix_0 = {}
tx_used = []
for _, row in inputs[['input_value', 'key_offset', 'transaction_hash']].iterrows():
    key_offset = row.key_offset.split('[')[1].split(']')[0]
    value = row.input_value
    outs = get_transactions(int(key_offset), int(value))
    if key_offset not in k_offsets_mix_0.keys():
        k_offsets_mix_0[key_offset] = [{'block': outs['outs'][0]['height'], 'key': outs['outs'][0]['key'], 'amount': value }]
    else:
        k_offsets_mix_0[key_offset].append({'block': outs['outs'][0]['height'], 'key': outs['outs'][0]['key'], 'amount': value })
    tx_used.append(outs['outs'][0]['key'])

With this last dictionary, we have the information of each key_offset used in the transactions with mixin equal to 0. As the mixins is 0, the transactions that appears is 100% the one being spend. If this key it is used in another transaction, we will know that it is not the real one as it has been previosuly spent.

In [64]:
query = """MATCH (i:Input)-[:TX_INPUT]->(t:Transactions)
            WHERE i.mixin <> '0'
            RETURN i, t"""

with driver.session() as session:
    data = to_list(session.run(query=query))
    
    rows = []
    for record in data:
        input_node = record['i']
        transaction_node = record['t']
        row = {
                    'input_mixin': input_node.get('mixin'),
                    'input_anonset': input_node.get('anonset'),
                    'input_id': input_node.get('id'),
                    'input_value': input_node.get('value'),
                    'key_offset': input_node.get('key_offset'),
                    'transaction_fee': transaction_node.get('fee'),
                    'transaction_id': transaction_node.get('id'),
                    'transaction_hash': transaction_node.get('hash')
                }
        rows.append(row)
inputs_mul_mix = pd.DataFrame(rows)
inputs_mul_mix

,input_mixin,input_anonset,input_id,input_value,key_offset,transaction_fee,transaction_id,transaction_hash
0,1,351,i767,10000000000000,"[182, 126]",2812564057,t407,53d0a3e54acaab8d3083e72d81b9afdeded7081894b1ca...
1,1,28,i766,4000000000000,"[21, 3]",2812564057,t407,53d0a3e54acaab8d3083e72d81b9afdeded7081894b1ca...
2,1,353,i769,10000000000000,"[232, 47]",4995647194,t410,3120ca4227a2845f24882dd55410354b9b01f626f4f0f5...
3,1,38,i770,700000000000,"[20, 5]",4995647194,t410,3120ca4227a2845f24882dd55410354b9b01f626f4f0f5...
4,1,47,i768,7000000000,"[15, 19]",4995647194,t410,3120ca4227a2845f24882dd55410354b9b01f626f4f0f5...
...,...,...,...,...,...,...,...,...
3870,9,1600,i4640,10000000000000,"[321, 109, 91, 230, 243, 69, 82, 49, 61, 145]",14954818413,t1891,118057d4d2998cefaebd659e83444d6d60114146b6a798...
3871,9,144,i4637,900000000000,"[44, 15, 24, 17, 3, 4, 1, 4, 2, 9]",14954818413,t1891,118057d4d2998cefaebd659e83444d6d60114146b6a798...
3872,9,1095,i4633,500000000000,"[120, 242, 194, 42, 313, 37, 6, 5, 2, 30]",14954818413,t1891,118057d4d2998cefaebd659e83444d6d60114146b6a798...
3873,9,293,i4639,600000000000,"[118, 25, 10, 19, 11, 13, 25, 15, 12, 21]",14954818413,t1891,118057d4d2998cefaebd659e83444d6d60114146b6a798...
3874,9,249,i4636,7000000000,"[92, 13, 10, 29, 11, 1, 47, 6, 33, 2]",14954818413,t1891,118057d4d2998cefaebd659e83444d6d60114146b6a798...

In [65]:
total_mixins = {'1': 0, '3': 0, '9': 0} 
vul_mixins = {'1': 0, '3': 0, '9': 0}
for x, row in inputs_mul_mix[['input_value', 'key_offset', 'transaction_hash', 'input_mixin']][:2000].iterrows():
    key_offset = row.key_offset.split('[')[1].split(']')[0].split(',')
    value = row.input_value
    num_mixin = row.input_mixin
    for i, key in enumerate(key_offset):
        total_mixins[str(num_mixin)] += 1
        key_i = int(key)
        out = get_transactions(key_i, int(value))
        if out['outs'][0]['key'] in tx_used:
            if num_mixin == 1:
                # If a transaction with 2 inputs uses one of the used inputs of our list,
                # we can also addthe other input in the list since it will be another used output
                tx_used.append(get_transactions(int(key_offset[1-i]), int(value))['outs'][0]['key'])
            vul_mixins[str(num_mixin)] += 1
            4
    print('-----------')
    print(x)

-----------
0
-----------
1
-----------
2
-----------
3
-----------
4
-----------
5
-----------
6
-----------
7
-----------
8
-----------
9
-----------
10
-----------
11
-----------
12
-----------
13
-----------
14
-----------
15
-----------
16
-----------
17
-----------
18
-----------
19
-----------
20
-----------
21
-----------
22
-----------
23
-----------
24
-----------
25
-----------
26
-----------
27
-----------
28
-----------
29
-----------
30
-----------
31
-----------
32
-----------
33
-----------
34
-----------
35
-----------
36
-----------
37
-----------
38
-----------
39
-----------
40
-----------
41
-----------
42
-----------
43
-----------
44
-----------
45
-----------
46
-----------
47
-----------
48
-----------
49
-----------
50
-----------
51
-----------
52
-----------
53
-----------
54
-----------
55
-----------
56
-----------
57
-----------
58
-----------
59
-----------
60
-----------
61
-----------
62
-----------
63
-----------
64
-----------
65
-----------
66
-----------
67
-----------
68
-----------
69
-----------
70
-----------
71
-----------
72
-----------
73
-----------
74
-----------
75
-----------
76
-----------
77
-----------
78
-----------
79
-----------
80
-----------
81
-----------
82
-----------
83
-----------
84
-----------
85
-----------
86
-----------
87
-----------
88
-----------
89
-----------
90
-----------
91
-----------
92
-----------
93
-----------
94
-----------
95
-----------
96
-----------
97
-----------
98
-----------
99
-----------
100
-----------
101
-----------
102
-----------
103
-----------
104
-----------
105
-----------
106
-----------
107
-----------
108
-----------
109
-----------
110
-----------
111
-----------
112
-----------
113
-----------
114
-----------
115
-----------
116
-----------
117
-----------
118
-----------
119
-----------
120
-----------
121
-----------
122
-----------
123
-----------
124
-----------
125
-----------
126
-----------
127
-----------
128
-----------
129
-----------
130
-----------
131
-----------
132
-----------
133
-----------
134
-----------
135
-----------
136
-----------
137
-----------
138
-----------
139
-----------
140
-----------
141
-----------
142
-----------
143
-----------
144
-----------
145
-----------
146
-----------
147
-----------
148
-----------
149
-----------
150
-----------
151
-----------
152
-----------
153
-----------
154
-----------
155
-----------
156
-----------
157
-----------
158
-----------
159
-----------
160
-----------
161
-----------
162
-----------
163
-----------
164
-----------
165
-----------
166
-----------
167
-----------
168
-----------
169
-----------
170
-----------
171
-----------
172
-----------
173
-----------
174
-----------
175
-----------
176
-----------
177
-----------
178
-----------
179
-----------
180
-----------
181
-----------
182
-----------
183
-----------
184
-----------
185
-----------
186
-----------
187
-----------
188
-----------
189
-----------
190
-----------
191
-----------
192
-----------
193
-----------
194
-----------
195
-----------
196
-----------
197
-----------
198
-----------
199
-----------
200
-----------
201
-----------
202
-----------
203
-----------
204
-----------
205
-----------
206
-----------
207
-----------
208
-----------
209
-----------
210
-----------
211
-----------
212
-----------
213
-----------
214
-----------
215
-----------
216
-----------
217
-----------
218
-----------
219
-----------
220
-----------
221
-----------
222
-----------
223
-----------
224
-----------
225
-----------
226
-----------
227
-----------
228
-----------
229
-----------
230
-----------
231
-----------
232
-----------
233
-----------
234
-----------
235
-----------
236
-----------
237
-----------
238
-----------
239
-----------
240
-----------
241
-----------
242
-----------
243
-----------
244
-----------
245
-----------
246
-----------
247
-----------
248
-----------
249
-----------
250
-----------
251
-----------
252
-----------
253
-----------
254
-----------
255
-----------
256
-----------
257
-----------
258
-----------
259
-----------
260
-----------
261
-----------
262
-----------
263
-----------
264
-----------
265
-----------
266
-----------
267
-----------
268
-----------
269
-----------
270
-----------
271
-----------
272
-----------
273
-----------
274
-----------
275
-----------
276
-----------
277
-----------
278
-----------
279
-----------
280
-----------
281
-----------
282
-----------
283
-----------
284
-----------
285
-----------
286
-----------
287
-----------
288
-----------
289
-----------
290
-----------
291
-----------
292
-----------
293
-----------
294
-----------
295
-----------
296
-----------
297
-----------
298
-----------
299
-----------
300
-----------
301
-----------
302
-----------
303
-----------
304
-----------
305
-----------
306
-----------
307
-----------
308
-----------
309
-----------
310
-----------
311
-----------
312
-----------
313
-----------
314
-----------
315
-----------
316
-----------
317
-----------
318
-----------
319
-----------
320
-----------
321
-----------
322
-----------
323
-----------
324
-----------
325
-----------
326
-----------
327
-----------
328
-----------
329
-----------
330
-----------
331
-----------
332
-----------
333
-----------
334
-----------
335
-----------
336
-----------
337
-----------
338
-----------
339
-----------
340
-----------
341
-----------
342
-----------
343
-----------
344
-----------
345
-----------
346
-----------
347
-----------
348
-----------
349
-----------
350
-----------
351
-----------
352
-----------
353
-----------
354
-----------
355
-----------
356
-----------
357
-----------
358
-----------
359
-----------
360
-----------
361
-----------
362
-----------
363
-----------
364
-----------
365
-----------
366
-----------
367
-----------
368
-----------
369
-----------
370
-----------
371
-----------
372
-----------
373
-----------
374
-----------
375
-----------
376
-----------
377
-----------
378
-----------
379
-----------
380
-----------
381
-----------
382
-----------
383
-----------
384
-----------
385
-----------
386
-----------
387
-----------
388
-----------
389
-----------
390
-----------
391
-----------
392
-----------
393
-----------
394
-----------
395
-----------
396
-----------
397
-----------
398
-----------
399
-----------
400
-----------
401
-----------
402
-----------
403
-----------
404
-----------
405
-----------
406
-----------
407
-----------
408
-----------
409
-----------
410
-----------
411
-----------
412
-----------
413
-----------
414
-----------
415
-----------
416
-----------
417
-----------
418
-----------
419
-----------
420
-----------
421
-----------
422
-----------
423
-----------
424
-----------
425
-----------
426
-----------
427
-----------
428
-----------
429
-----------
430
-----------
431
-----------
432
-----------
433
-----------
434
-----------
435
-----------
436
-----------
437
-----------
438
-----------
439
-----------
440
-----------
441
-----------
442
-----------
443
-----------
444
-----------
445
-----------
446
-----------
447
-----------
448
-----------
449
-----------
450
-----------
451
-----------
452
-----------
453
-----------
454
-----------
455
-----------
456
-----------
457
-----------
458
-----------
459
-----------
460
-----------
461
-----------
462
-----------
463
-----------
464
-----------
465
-----------
466
-----------
467
-----------
468
-----------
469
-----------
470
-----------
471
-----------
472
-----------
473
-----------
474
-----------
475
-----------
476
-----------
477
-----------
478
-----------
479
-----------
480
-----------
481
-----------
482
-----------
483
-----------
484
-----------
485
-----------
486
-----------
487
-----------
488
-----------
489
-----------
490
-----------
491
-----------
492
-----------
493
-----------
494
-----------
495
-----------
496
-----------
497
-----------
498
-----------
499
-----------
500
-----------
501
-----------
502
-----------
503
-----------
504
-----------
505
-----------
506
-----------
507
-----------
508
-----------
509
-----------
510
-----------
511
-----------
512
-----------
513
-----------
514
-----------
515
-----------
516
-----------
517
-----------
518
-----------
519
-----------
520
-----------
521
-----------
522
-----------
523
-----------
524
-----------
525
-----------
526
-----------
527
-----------
528
-----------
529
-----------
530
-----------
531
-----------
532
-----------
533
-----------
534
-----------
535
-----------
536
-----------
537
-----------
538
-----------
539
-----------
540
-----------
541
-----------
542
-----------
543
-----------
544
-----------
545
-----------
546
-----------
547
-----------
548
-----------
549
-----------
550
-----------
551
-----------
552
-----------
553
-----------
554
-----------
555
-----------
556
-----------
557
-----------
558
-----------
559
-----------
560
-----------
561
-----------
562
-----------
563
-----------
564
-----------
565
-----------
566
-----------
567
-----------
568
-----------
569
-----------
570
-----------
571
-----------
572
-----------
573
-----------
574
-----------
575
-----------
576
-----------
577
-----------
578
-----------
579
-----------
580
-----------
581
-----------
582
-----------
583
-----------
584
-----------
585
-----------
586
-----------
587
-----------
588
-----------
589
-----------
590
-----------
591
-----------
592
-----------
593
-----------
594
-----------
595
-----------
596
-----------
597
-----------
598
-----------
599
-----------
600
-----------
601
-----------
602
-----------
603
-----------
604
-----------
605
-----------
606
-----------
607
-----------
608
-----------
609
-----------
610
-----------
611
-----------
612
-----------
613
-----------
614
-----------
615
-----------
616
-----------
617
-----------
618
-----------
619
-----------
620
-----------
621
-----------
622
-----------
623
-----------
624
-----------
625
-----------
626
-----------
627
-----------
628
-----------
629
-----------
630
-----------
631
-----------
632
-----------
633
-----------
634
-----------
635
-----------
636
-----------
637
-----------
638
-----------
639
-----------
640
-----------
641
-----------
642
-----------
643
-----------
644
-----------
645
-----------
646
-----------
647
-----------
648
-----------
649
-----------
650
-----------
651
-----------
652
-----------
653
-----------
654
-----------
655
-----------
656
-----------
657
-----------
658
-----------
659
-----------
660
-----------
661
-----------
662
-----------
663
-----------
664
-----------
665
-----------
666
-----------
667
-----------
668
-----------
669
-----------
670
-----------
671
-----------
672
-----------
673
-----------
674
-----------
675
-----------
676
-----------
677
-----------
678
-----------
679
-----------
680
-----------
681
-----------
682
-----------
683
-----------
684
-----------
685
-----------
686
-----------
687
-----------
688
-----------
689
-----------
690
-----------
691
-----------
692
-----------
693
-----------
694
-----------
695
-----------
696
-----------
697
-----------
698
-----------
699
-----------
700
-----------
701
-----------
702
-----------
703
-----------
704
-----------
705
-----------
706
-----------
707
-----------
708
-----------
709
-----------
710
-----------
711
-----------
712
-----------
713
-----------
714
-----------
715
-----------
716
-----------
717
-----------
718
-----------
719
-----------
720
-----------
721
-----------
722
-----------
723
-----------
724
-----------
725
-----------
726
-----------
727
-----------
728
-----------
729
-----------
730
-----------
731
-----------
732
-----------
733
-----------
734
-----------
735
-----------
736
-----------
737
-----------
738
-----------
739
-----------
740
-----------
741
-----------
742
-----------
743
-----------
744
-----------
745
-----------
746
-----------
747
-----------
748
-----------
749
-----------
750
-----------
751
-----------
752
-----------
753
-----------
754
-----------
755
-----------
756
-----------
757
-----------
758
-----------
759
-----------
760
-----------
761
-----------
762
-----------
763
-----------
764
-----------
765
-----------
766
-----------
767
-----------
768
-----------
769
-----------
770
-----------
771
-----------
772
-----------
773
-----------
774
-----------
775
-----------
776
-----------
777
-----------
778
-----------
779
-----------
780
-----------
781
-----------
782
-----------
783
-----------
784
-----------
785
-----------
786
-----------
787
-----------
788
-----------
789
-----------
790
-----------
791
-----------
792
-----------
793
-----------
794
-----------
795
-----------
796
-----------
797
-----------
798
-----------
799
-----------
800
-----------
801
-----------
802
-----------
803
-----------
804
-----------
805
-----------
806
-----------
807
-----------
808
-----------
809
-----------
810
-----------
811
-----------
812
-----------
813
-----------
814
-----------
815
-----------
816
-----------
817
-----------
818
-----------
819
-----------
820
-----------
821
-----------
822
-----------
823
-----------
824
-----------
825
-----------
826
-----------
827
-----------
828
-----------
829
-----------
830
-----------
831
-----------
832
-----------
833
-----------
834
-----------
835
-----------
836
-----------
837
-----------
838
-----------
839
-----------
840
-----------
841
-----------
842
-----------
843
-----------
844
-----------
845
-----------
846
-----------
847
-----------
848
-----------
849
-----------
850
-----------
851
-----------
852
-----------
853
-----------
854
-----------
855
-----------
856
-----------
857
-----------
858
-----------
859
-----------
860
-----------
861
-----------
862
-----------
863
-----------
864
-----------
865
-----------
866
-----------
867
-----------
868
-----------
869
-----------
870
-----------
871
-----------
872
-----------
873
-----------
874
-----------
875
-----------
876
-----------
877
-----------
878
-----------
879
-----------
880
-----------
881
-----------
882
-----------
883
-----------
884
-----------
885
-----------
886
-----------
887
-----------
888
-----------
889
-----------
890
-----------
891
-----------
892
-----------
893
-----------
894
-----------
895
-----------
896
-----------
897
-----------
898
-----------
899
-----------
900
-----------
901
-----------
902
-----------
903
-----------
904
-----------
905
-----------
906
-----------
907
-----------
908
-----------
909
-----------
910
-----------
911
-----------
912
-----------
913
-----------
914
-----------
915
-----------
916
-----------
917
-----------
918
-----------
919
-----------
920
-----------
921
-----------
922
-----------
923
-----------
924
-----------
925
-----------
926
-----------
927
-----------
928
-----------
929
-----------
930
-----------
931
-----------
932
-----------
933
-----------
934
-----------
935
-----------
936
-----------
937
-----------
938
-----------
939
-----------
940
-----------
941
-----------
942
-----------
943
-----------
944
-----------
945
-----------
946
-----------
947
-----------
948
-----------
949
-----------
950
-----------
951
-----------
952
-----------
953
-----------
954
-----------
955
-----------
956
-----------
957
-----------
958
-----------
959
-----------
960
-----------
961
-----------
962
-----------
963
-----------
964
-----------
965
-----------
966
-----------
967
-----------
968
-----------
969
-----------
970
-----------
971
-----------
972
-----------
973
-----------
974
-----------
975
-----------
976
-----------
977
-----------
978
-----------
979
-----------
980
-----------
981
-----------
982
-----------
983
-----------
984
-----------
985
-----------
986
-----------
987
-----------
988
-----------
989
-----------
990
-----------
991
-----------
992
-----------
993
-----------
994
-----------
995
-----------
996
-----------
997
-----------
998
-----------
999
-----------
1000
-----------
1001
-----------
1002
-----------
1003
-----------
1004
-----------
1005
-----------
1006
-----------
1007
-----------
1008
-----------
1009
-----------
1010
-----------
1011
-----------
1012
-----------
1013
-----------
1014
-----------
1015
-----------
1016
-----------
1017
-----------
1018
-----------
1019
-----------
1020
-----------
1021
-----------
1022
-----------
1023
-----------
1024
-----------
1025
-----------
1026
-----------
1027
-----------
1028
-----------
1029
-----------
1030
-----------
1031
-----------
1032
-----------
1033
-----------
1034
-----------
1035
-----------
1036
-----------
1037
-----------
1038
-----------
1039
-----------
1040
-----------
1041
-----------
1042
-----------
1043
-----------
1044
-----------
1045
-----------
1046
-----------
1047
-----------
1048
-----------
1049
-----------
1050
-----------
1051
-----------
1052
-----------
1053
-----------
1054
-----------
1055
-----------
1056
-----------
1057
-----------
1058
-----------
1059
-----------
1060
-----------
1061
-----------
1062
-----------
1063
-----------
1064
-----------
1065
-----------
1066
-----------
1067
-----------
1068
-----------
1069
-----------
1070
-----------
1071
-----------
1072
-----------
1073
-----------
1074
-----------
1075
-----------
1076
-----------
1077
-----------
1078
-----------
1079
-----------
1080
-----------
1081
-----------
1082
-----------
1083
-----------
1084
-----------
1085
-----------
1086
-----------
1087
-----------
1088
-----------
1089
-----------
1090
-----------
1091
-----------
1092
-----------
1093
-----------
1094
-----------
1095
-----------
1096
-----------
1097
-----------
1098
-----------
1099
-----------
1100
-----------
1101
-----------
1102
-----------
1103
-----------
1104
-----------
1105
-----------
1106
-----------
1107
-----------
1108
-----------
1109
-----------
1110
-----------
1111
-----------
1112
-----------
1113
-----------
1114
-----------
1115
-----------
1116
-----------
1117
-----------
1118
-----------
1119
-----------
1120
-----------
1121
-----------
1122
-----------
1123
-----------
1124
-----------
1125
-----------
1126
-----------
1127
-----------
1128
-----------
1129
-----------
1130
-----------
1131
-----------
1132
-----------
1133
-----------
1134
-----------
1135
-----------
1136
-----------
1137
-----------
1138
-----------
1139
-----------
1140
-----------
1141
-----------
1142
-----------
1143
-----------
1144
-----------
1145
-----------
1146
-----------
1147
-----------
1148
-----------
1149
-----------
1150
-----------
1151
-----------
1152
-----------
1153
-----------
1154
-----------
1155
-----------
1156
-----------
1157
-----------
1158
-----------
1159
-----------
1160
-----------
1161
-----------
1162
-----------
1163
-----------
1164
-----------
1165
-----------
1166
-----------
1167
-----------
1168
-----------
1169
-----------
1170
-----------
1171
-----------
1172
-----------
1173
-----------
1174
-----------
1175
-----------
1176
-----------
1177
-----------
1178
-----------
1179
-----------
1180
-----------
1181
-----------
1182
-----------
1183
-----------
1184
-----------
1185
-----------
1186
-----------
1187
-----------
1188
-----------
1189
-----------
1190
-----------
1191
-----------
1192
-----------
1193
-----------
1194
-----------
1195
-----------
1196
-----------
1197
-----------
1198
-----------
1199
-----------
1200
-----------
1201
-----------
1202
-----------
1203
-----------
1204
-----------
1205
-----------
1206
-----------
1207
-----------
1208
-----------
1209
-----------
1210
-----------
1211
-----------
1212
-----------
1213
-----------
1214
-----------
1215
-----------
1216
-----------
1217
-----------
1218
-----------
1219
-----------
1220
-----------
1221
-----------
1222
-----------
1223
-----------
1224
-----------
1225
-----------
1226
-----------
1227
-----------
1228
-----------
1229
-----------
1230
-----------
1231
-----------
1232
-----------
1233
-----------
1234
-----------
1235
-----------
1236
-----------
1237
-----------
1238
-----------
1239
-----------
1240
-----------

In [68]:
for x, row in inputs_mul_mix[['input_value', 'key_offset', 'transaction_hash', 'input_mixin']][3000:].iterrows():
    key_offset = row.key_offset.split('[')[1].split(']')[0].split(',')
    value = row.input_value
    num_mixin = row.input_mixin
    for i, key in enumerate(key_offset):
        total_mixins[str(num_mixin)] += 1
        key_i = int(key)
        out = get_transactions(key_i, int(value))
        if out['outs'][0]['key'] in tx_used:
            if num_mixin == 1:
                # If a transaction with 2 inputs uses one of the used inputs of our list,
                # we can also addthe other input in the list since it will be another used output
                tx_used.append(get_transactions(int(key_offset[1-i]), int(value))['outs'][0]['key'])
            vul_mixins[str(num_mixin)] += 1
            4
    print('-----------')
    print(x)

-----------
3000
-----------
3001
-----------
3002
-----------
3003
-----------
3004
-----------
3005
-----------
3006
-----------
3007
-----------
3008
-----------
3009
-----------
3010
-----------
3011
-----------
3012
-----------
3013
-----------
3014
-----------
3015
-----------
3016
-----------
3017
-----------
3018
-----------
3019
-----------
3020
-----------
3021
-----------
3022
-----------
3023
-----------
3024
-----------
3025
-----------
3026
-----------
3027
-----------
3028
-----------
3029
-----------
3030
-----------
3031
-----------
3032
-----------
3033
-----------
3034
-----------
3035
-----------
3036
-----------
3037
-----------
3038
-----------
3039
-----------
3040
-----------
3041
-----------
3042
-----------
3043
-----------
3044
-----------
3045
-----------
3046
-----------
3047
-----------
3048
-----------
3049
-----------
3050
-----------
3051
-----------
3052
-----------
3053
-----------
3054
-----------
3055
-----------
3056
-----------
3057
-----------
3058
-----------
3059
-----------
3060
-----------
3061
-----------
3062
-----------
3063
-----------
3064
-----------
3065
-----------
3066
-----------
3067
-----------
3068
-----------
3069
-----------
3070
-----------
3071
-----------
3072
-----------
3073
-----------
3074
-----------
3075
-----------
3076
-----------
3077
-----------
3078
-----------
3079
-----------
3080
-----------
3081
-----------
3082
-----------
3083
-----------
3084
-----------
3085
-----------
3086
-----------
3087
-----------
3088
-----------
3089
-----------
3090
-----------
3091
-----------
3092
-----------
3093
-----------
3094
-----------
3095
-----------
3096
-----------
3097
-----------
3098
-----------
3099
-----------
3100
-----------
3101
-----------
3102
-----------
3103
-----------
3104
-----------
3105
-----------
3106
-----------
3107
-----------
3108
-----------
3109
-----------
3110
-----------
3111
-----------
3112
-----------
3113
-----------
3114
-----------
3115
-----------
3116
-----------
3117
-----------
3118
-----------
3119
-----------
3120
-----------
3121
-----------
3122
-----------
3123
-----------
3124
-----------
3125
-----------
3126
-----------
3127
-----------
3128
-----------
3129
-----------
3130
-----------
3131
-----------
3132
-----------
3133
-----------
3134
-----------
3135
-----------
3136
-----------
3137
-----------
3138
-----------
3139
-----------
3140
-----------
3141
-----------
3142
-----------
3143
-----------
3144
-----------
3145
-----------
3146
-----------
3147
-----------
3148
-----------
3149
-----------
3150
-----------
3151
-----------
3152
-----------
3153
-----------
3154
-----------
3155
-----------
3156
-----------
3157
-----------
3158
-----------
3159
-----------
3160
-----------
3161
-----------
3162
-----------
3163
-----------
3164
-----------
3165
-----------
3166
-----------
3167
-----------
3168
-----------
3169
-----------
3170
-----------
3171
-----------
3172
-----------
3173
-----------
3174
-----------
3175
-----------
3176
-----------
3177
-----------
3178
-----------
3179
-----------
3180
-----------
3181
-----------
3182
-----------
3183
-----------
3184
-----------
3185
-----------
3186
-----------
3187
-----------
3188
-----------
3189
-----------
3190
-----------
3191
-----------
3192
-----------
3193
-----------
3194
-----------
3195
-----------
3196
-----------
3197
-----------
3198
-----------
3199
-----------
3200
-----------
3201
-----------
3202
-----------
3203
-----------
3204
-----------
3205
-----------
3206
-----------
3207
-----------
3208
-----------
3209
-----------
3210
-----------
3211
-----------
3212
-----------
3213
-----------
3214
-----------
3215
-----------
3216
-----------
3217
-----------
3218
-----------
3219
-----------
3220
-----------
3221
-----------
3222
-----------
3223
-----------
3224
-----------
3225
-----------
3226
-----------
3227
-----------
3228
-----------
3229
-----------
3230
-----------
3231
-----------
3232
-----------
3233
-----------
3234
-----------
3235
-----------
3236
-----------
3237
-----------
3238
-----------
3239
-----------
3240
-----------
3241
-----------
3242
-----------
3243
-----------
3244
-----------
3245
-----------
3246
-----------
3247
-----------
3248
-----------
3249
-----------
3250
-----------
3251
-----------
3252
-----------
3253
-----------
3254
-----------
3255
-----------
3256
-----------
3257
-----------
3258
-----------
3259
-----------
3260
-----------
3261
-----------
3262
-----------
3263
-----------
3264
-----------
3265
-----------
3266
-----------
3267
-----------
3268
-----------
3269
-----------
3270
-----------
3271
-----------
3272
-----------
3273
-----------
3274
-----------
3275
-----------
3276
-----------
3277
-----------
3278
-----------
3279
-----------
3280
-----------
3281
-----------
3282
-----------
3283
-----------
3284
-----------
3285
-----------
3286
-----------
3287
-----------
3288
-----------
3289
-----------
3290
-----------
3291
-----------
3292
-----------
3293
-----------
3294
-----------
3295
-----------
3296
-----------
3297
-----------
3298
-----------
3299
-----------
3300
-----------
3301
-----------
3302
-----------
3303
-----------
3304
-----------
3305
-----------
3306
-----------
3307
-----------
3308
-----------
3309
-----------
3310
-----------
3311
-----------
3312
-----------
3313
-----------
3314
-----------
3315
-----------
3316
-----------
3317
-----------
3318
-----------
3319
-----------
3320
-----------
3321
-----------
3322
-----------
3323
-----------
3324
-----------
3325
-----------
3326
-----------
3327
-----------
3328
-----------
3329
-----------
3330
-----------
3331
-----------
3332
-----------
3333
-----------
3334
-----------
3335
-----------
3336
-----------
3337
-----------
3338
-----------
3339
-----------
3340
-----------
3341
-----------
3342
-----------
3343
-----------
3344
-----------
3345
-----------
3346
-----------
3347
-----------
3348
-----------
3349
-----------
3350
-----------
3351
-----------
3352
-----------
3353
-----------
3354
-----------
3355
-----------
3356
-----------
3357
-----------
3358
-----------
3359
-----------
3360
-----------
3361
-----------
3362
-----------
3363
-----------
3364
-----------
3365
-----------
3366
-----------
3367
-----------
3368
-----------
3369
-----------
3370
-----------
3371
-----------
3372
-----------
3373
-----------
3374
-----------
3375
-----------
3376
-----------
3377
-----------
3378
-----------
3379
-----------
3380
-----------
3381
-----------
3382
-----------
3383
-----------
3384
-----------
3385
-----------
3386
-----------
3387
-----------
3388
-----------
3389
-----------
3390
-----------
3391
-----------
3392
-----------
3393
-----------
3394
-----------
3395
-----------
3396
-----------
3397
-----------
3398
-----------
3399
-----------
3400
-----------
3401
-----------
3402
-----------
3403
-----------
3404
-----------
3405
-----------
3406
-----------
3407
-----------
3408
-----------
3409
-----------
3410
-----------
3411
-----------
3412
-----------
3413
-----------
3414
-----------
3415
-----------
3416
-----------
3417
-----------
3418
-----------
3419
-----------
3420
-----------
3421
-----------
3422
-----------
3423
-----------
3424
-----------
3425
-----------
3426
-----------
3427
-----------
3428
-----------
3429
-----------
3430
-----------
3431
-----------
3432
-----------
3433
-----------
3434
-----------
3435
-----------
3436
-----------
3437
-----------
3438
-----------
3439
-----------
3440
-----------
3441
-----------
3442
-----------
3443
-----------
3444
-----------
3445
-----------
3446
-----------
3447
-----------
3448
-----------
3449
-----------
3450
-----------
3451
-----------
3452
-----------
3453
-----------
3454
-----------
3455
-----------
3456
-----------
3457
-----------
3458
-----------
3459
-----------
3460
-----------
3461
-----------
3462
-----------
3463
-----------
3464
-----------
3465
-----------
3466
-----------
3467
-----------
3468
-----------
3469
-----------
3470
-----------
3471
-----------
3472
-----------
3473
-----------
3474
-----------
3475
-----------
3476
-----------
3477
-----------
3478
-----------
3479
-----------
3480
-----------
3481
-----------
3482
-----------
3483
-----------
3484
-----------
3485
-----------
3486
-----------
3487
-----------
3488
-----------
3489
-----------
3490
-----------
3491
-----------
3492
-----------
3493
-----------
3494
-----------
3495
-----------
3496
-----------
3497
-----------
3498
-----------
3499
-----------
3500
-----------
3501
-----------
3502
-----------
3503
-----------
3504
-----------
3505
-----------
3506
-----------
3507
-----------
3508
-----------
3509
-----------
3510
-----------
3511
-----------
3512
-----------
3513
-----------
3514
-----------
3515
-----------
3516
-----------
3517
-----------
3518
-----------
3519
-----------
3520
-----------
3521
-----------
3522
-----------
3523
-----------
3524
-----------
3525
-----------
3526
-----------
3527
-----------
3528
-----------
3529
-----------
3530
-----------
3531
-----------
3532
-----------
3533
-----------
3534
-----------
3535
-----------
3536
-----------
3537
-----------
3538
-----------
3539
-----------
3540
-----------
3541
-----------
3542
-----------
3543
-----------
3544
-----------
3545
-----------
3546
-----------
3547
-----------
3548
-----------
3549
-----------
3550
-----------
3551
-----------
3552
-----------
3553
-----------
3554
-----------
3555
-----------
3556
-----------
3557
-----------
3558
-----------
3559
-----------
3560
-----------
3561
-----------
3562
-----------
3563
-----------
3564
-----------
3565
-----------
3566
-----------
3567
-----------
3568
-----------
3569
-----------
3570
-----------
3571
-----------
3572
-----------
3573
-----------
3574
-----------
3575
-----------
3576
-----------
3577
-----------
3578
-----------
3579
-----------
3580
-----------
3581
-----------
3582
-----------
3583
-----------
3584
-----------
3585
-----------
3586
-----------
3587
-----------
3588
-----------
3589
-----------
3590
-----------
3591
-----------
3592
-----------
3593
-----------
3594
-----------
3595
-----------
3596
-----------
3597
-----------
3598
-----------
3599
-----------
3600
-----------
3601
-----------
3602
-----------
3603
-----------
3604
-----------
3605
-----------
3606
-----------
3607
-----------
3608
-----------
3609
-----------
3610
-----------
3611
-----------
3612
-----------
3613
-----------
3614
-----------
3615
-----------
3616
-----------
3617
-----------
3618
-----------
3619
-----------
3620
-----------
3621
-----------
3622
-----------
3623
-----------
3624
-----------
3625
-----------
3626
-----------
3627
-----------
3628
-----------
3629
-----------
3630
-----------
3631
-----------
3632
-----------
3633
-----------
3634
-----------
3635
-----------
3636
-----------
3637
-----------
3638
-----------
3639
-----------
3640
-----------
3641
-----------
3642
-----------
3643
-----------
3644
-----------
3645
-----------
3646
-----------
3647
-----------
3648
-----------
3649
-----------
3650
-----------
3651
-----------
3652
-----------
3653
-----------
3654
-----------
3655
-----------
3656
-----------
3657
-----------
3658
-----------
3659
-----------
3660
-----------
3661
-----------
3662
-----------
3663
-----------
3664
-----------
3665
-----------
3666
-----------
3667
-----------
3668
-----------
3669
-----------
3670
-----------
3671
-----------
3672
-----------
3673
-----------
3674
-----------
3675
-----------
3676
-----------
3677
-----------
3678
-----------
3679
-----------
3680
-----------
3681
-----------
3682
-----------
3683
-----------
3684
-----------
3685
-----------
3686
-----------
3687
-----------
3688
-----------
3689
-----------
3690
-----------
3691
-----------
3692
-----------
3693
-----------
3694
-----------
3695
-----------
3696
-----------
3697
-----------
3698
-----------
3699
-----------
3700
-----------
3701
-----------
3702
-----------
3703
-----------
3704
-----------
3705
-----------
3706
-----------
3707
-----------
3708
-----------
3709
-----------
3710
-----------
3711
-----------
3712
-----------
3713
-----------
3714
-----------
3715
-----------
3716
-----------
3717
-----------
3718
-----------
3719
-----------
3720
-----------
3721
-----------
3722
-----------
3723
-----------
3724
-----------
3725
-----------
3726
-----------
3727
-----------
3728
-----------
3729
-----------
3730
-----------
3731
-----------
3732
-----------
3733
-----------
3734
-----------
3735
-----------
3736
-----------
3737
-----------
3738
-----------
3739
-----------
3740
-----------
3741
-----------
3742
-----------
3743
-----------
3744
-----------
3745
-----------
3746
-----------
3747
-----------
3748
-----------
3749
-----------
3750
-----------
3751
-----------
3752
-----------
3753
-----------
3754
-----------
3755
-----------
3756
-----------
3757
-----------
3758
-----------
3759
-----------
3760
-----------
3761
-----------
3762
-----------
3763
-----------
3764
-----------
3765
-----------
3766
-----------
3767
-----------
3768
-----------
3769
-----------
3770
-----------
3771
-----------
3772
-----------
3773
-----------
3774
-----------
3775
-----------
3776
-----------
3777
-----------
3778
-----------
3779
-----------
3780
-----------
3781
-----------
3782
-----------
3783
-----------
3784
-----------
3785
-----------
3786
-----------
3787
-----------
3788
-----------
3789
-----------
3790
-----------
3791
-----------
3792
-----------
3793
-----------
3794
-----------
3795
-----------
3796
-----------
3797
-----------
3798
-----------
3799
-----------
3800
-----------
3801
-----------
3802
-----------
3803
-----------
3804
-----------
3805
-----------
3806
-----------
3807
-----------
3808
-----------
3809
-----------
3810
-----------
3811
-----------
3812
-----------
3813
-----------
3814
-----------
3815
-----------
3816
-----------
3817
-----------
3818
-----------
3819
-----------
3820
-----------
3821
-----------
3822
-----------
3823
-----------
3824
-----------
3825
-----------
3826
-----------
3827
-----------
3828
-----------
3829
-----------
3830
-----------
3831
-----------
3832
-----------
3833
-----------
3834
-----------
3835
-----------
3836
-----------
3837
-----------
3838
-----------
3839
-----------
3840
-----------
3841
-----------
3842
-----------
3843
-----------
3844
-----------
3845
-----------
3846
-----------
3847
-----------
3848
-----------
3849
-----------
3850
-----------
3851
-----------
3852
-----------
3853
-----------
3854
-----------
3855
-----------
3856
-----------
3857
-----------
3858
-----------
3859
-----------
3860
-----------
3861
-----------
3862
-----------
3863
-----------
3864
-----------
3865
-----------
3866
-----------
3867
-----------
3868
-----------
3869
-----------
3870
-----------
3871
-----------
3872
-----------
3873
-----------
3874

In [69]:
print("Persentage of deducible mixins with ring size equal to 2: ", vul_mixins['1']/total_mixins['1'])
print("Persentage of deducible mixins with ring size equal to 4: ", vul_mixins['3']/total_mixins['3'])
print("Persentage of deducible mixins with ring size equal to 10: ", vul_mixins['9']/total_mixins['9'])

Persentage of deducible mixins with ring size equal to 2:  0.3106060606060606
Persentage of deducible mixins with ring size equal to 4:  0.4846698113207547
Persentage of deducible mixins with ring size equal to 10:  0.48604510222959396

In [73]:

for _, row in inputs_mul_mix[['input_value', 'key_offset', 'transaction_hash', 'input_mixin']][inputs_mul_mix['input_mixin'] != '9'].iterrows():
    key_offset = row.key_offset.split('[')[1].split(']')[0].split(',')
    value = row.input_value
    num_mixin = row.input_mixin
    for i, key in enumerate(key_offset):
        total_mixins[str(num_mixin)] += 1
        key_i = int(key)
        out = get_transactions(key_i, int(value))
        if out['outs'][0]['key'] in tx_used:
            if num_mixin == 1:
                # If a transaction with 2 inputs uses one of the used inputs of our list,
                # we can also addthe other input in the list since it will be another used output
                tx_used.append(get_transactions(int(key_offset[1-i]), int(value))['outs'][0]['key'])
            print('-----------')
            print('Vul found')

-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found
-----------
Vul found

In [74]:

total_mixins_1000 = {'9': 0} 
vul_mixins_1000 = {'9': 0}
for _, row in inputs_mul_mix[['input_value', 'key_offset', 'transaction_hash', 'input_mixin']][inputs_mul_mix['input_mixin'] == '9'][:1001].iterrows():
    key_offset = row.key_offset.split('[')[1].split(']')[0].split(',')
    value = row.input_value
    num_mixin = row.input_mixin
    for i, key in enumerate(key_offset):
        total_mixins_1000[str(num_mixin)] += 1
        key_i = int(key)
        out = get_transactions(key_i, int(value))
        if out['outs'][0]['key'] in tx_used:
            if num_mixin == 1:
                # If a transaction with 2 inputs uses one of the used inputs of our list,
                # we can also addthe other input in the list since it will be another used output
                tx_used.append(get_transactions(int(key_offset[1-i]), int(value))['outs'][0]['key'])
            vul_mixins_1000[str(num_mixin)] += 1

In [75]:
total_mixins_2000 = {'9': 0} 
vul_mixins_2000 = {'9': 0}
for _, row in inputs_mul_mix[['input_value', 'key_offset', 'transaction_hash', 'input_mixin']][inputs_mul_mix['input_mixin'] == '9'][1001:2001].iterrows():
    key_offset = row.key_offset.split('[')[1].split(']')[0].split(',')
    value = row.input_value
    num_mixin = row.input_mixin
    for i, key in enumerate(key_offset):
        total_mixins_2000[str(num_mixin)] += 1
        key_i = int(key)
        out = get_transactions(key_i, int(value))
        if out['outs'][0]['key'] in tx_used:
            if num_mixin == 1:
                # If a transaction with 2 inputs uses one of the used inputs of our list,
                # we can also addthe other input in the list since it will be another used output
                tx_used.append(get_transactions(int(key_offset[1-i]), int(value))['outs'][0]['key'])
            vul_mixins_2000[str(num_mixin)] += 1

In [77]:
total_mixins_3000 = {'9': 0} 
vul_mixins_3000 = {'9': 0}
for _, row in inputs_mul_mix[['input_value', 'key_offset', 'transaction_hash', 'input_mixin']][inputs_mul_mix['input_mixin'] == '9'][2001:3001].iterrows():
    key_offset = row.key_offset.split('[')[1].split(']')[0].split(',')
    value = row.input_value
    num_mixin = row.input_mixin
    for i, key in enumerate(key_offset):
        total_mixins_3000[str(num_mixin)] += 1
        key_i = int(key)
        out = get_transactions(key_i, int(value))
        if out['outs'][0]['key'] in tx_used:
            if num_mixin == 1:
                # If a transaction with 2 inputs uses one of the used inputs of our list,
                # we can also addthe other input in the list since it will be another used output
                tx_used.append(get_transactions(int(key_offset[1-i]), int(value))['outs'][0]['key'])
            vul_mixins_3000[str(num_mixin)] += 1

In [78]:
total_mixins_3800 = {'9': 0} 
vul_mixins_3800 = {'9': 0}
for _, row in inputs_mul_mix[['input_value', 'key_offset', 'transaction_hash', 'input_mixin']][inputs_mul_mix['input_mixin'] == '9'][3001:].iterrows():
    key_offset = row.key_offset.split('[')[1].split(']')[0].split(',')
    value = row.input_value
    num_mixin = row.input_mixin
    for i, key in enumerate(key_offset):
        total_mixins_3800[str(num_mixin)] += 1
        key_i = int(key)
        out = get_transactions(key_i, int(value))
        if out['outs'][0]['key'] in tx_used:
            if num_mixin == 1:
                # If a transaction with 2 inputs uses one of the used inputs of our list,
                # we can also addthe other input in the list since it will be another used output
                tx_used.append(get_transactions(int(key_offset[1-i]), int(value))['outs'][0]['key'])
            vul_mixins_3800[str(num_mixin)] += 1

In [79]:
print("Persentage of deducible mixins with ring size equal to 10. First 1000: ", vul_mixins_1000['9']/total_mixins_1000['9'])
print("Persentage of deducible mixins with ring size equal to 10. First 1000: ", vul_mixins_2000['9']/total_mixins_2000['9'])
print("Persentage of deducible mixins with ring size equal to 10. First 1000: ", vul_mixins_3000['9']/total_mixins_3000['9'])
print("Persentage of deducible mixins with ring size equal to 10. First 1000: ", vul_mixins_3800['9']/total_mixins_3800['9'])

Persentage of deducible mixins with ring size equal to 10. First 1000:  0.5527472527472528
Persentage of deducible mixins with ring size equal to 10. First 1000:  0.4741
Persentage of deducible mixins with ring size equal to 10. First 1000:  0.4385
Persentage of deducible mixins with ring size equal to 10. First 1000:  0.43208955223880596